### PR TITLE
Rely on exponential backoff when requesting the cluster's status

### PR DESCRIPTION
**Pull request by oguzhanunlu**

### CODE REVIEW

**Review by chuwy — CHANGES_REQUESTED** [review]
I'm not sure I 100% agree with the taken strategy if I read the code right.

1. Overall 30 seconds sounds like a sensible default. Usually cluster becomes available within ~3-4 minutes, so the check manages to happen 6-9 times. We can lose ~29 seconds in worst case scenario, i.e. a cluster becomes available the next second after last check
2. What happens now is that we increase the pauses between check up to 10 minutes for _normally functioning_ clusters. If a cluster becomes available after 4 minutes our checks will happen in 1 + 2 + 4 mins, so 6 mins after DF started and 2 minutes after the cluster became available. So we effictively loose 2 mins, which is quite a lot. In other words, there's very small chance for a check to succeed in first 3 mins, but in 4-6 mins the chance is very high, so I think we should be increasing checks frequency with time
3. What _I think_ we need to do is to impose this backoff period not on nomrally functioning clusters, but on ones where we see this throughput error. Right now it just makes DF to fail, but out cluster is likely is still starting somewhere out there - we just need to be more polite with EMR service.

That's how I see the problem - happy to be proven to be wrong and give a green tick if I musunderstood something.

**Comment by oguzhanunlu** [comment]
Thanks for the quick review @chuwy , I also wasn't sure about the strategy.

> but on ones where we see this throughput error

Yeah it makes sense, first hit of the rate limit ex can be followed by the backoff strategy.

On the strategy, how about min (30 sec) - max (1 min) - factor (1.1) and jitter enabled so that we have 30 sec > 33 sec > 36.3 sec and so on? Compared to constant 30 sec, factor of 1.1 is a bit more polite. What do you think?

**Comment by chuwy** [comment]
What I meant is that the backoff strategy should be applied only on faulty pipelines, i.e. if you see a throughput exception, in normal circumstances it would harm more (delay the job).

Another point is that if we're going to backoff period - it should be a reverse backoff, i.e. 3 min, 1 min, 30 sec, 20 sec. It reduces the overall amount of calls, but also makes sure the job isn't stuck. 

I think this is what we need to do.

1. Follow above strategy: 3 min, 1 min, 30 sec, 20 sec, 15 sec, 15 sec, 15 sec... (although worth to check with someone if there's statistics on cluster startup time)
2. Whenever we hit a throughput exception (exactly this one) - instead of failing we add time

**Comment by oguzhanunlu** [comment]
Continuing at #69

**Pull request closed without merging**
